RANDOM_STATE: 42



drop_columns:
  - "id"
  - "pickup_datetime"
  - "store_and_fwd_flag"
  - "hour"
  - "month"
  - "day_of_week"

use_polynomial: True
polynomial:
  degree: 3
  include_bias: False

use_scaling: True
scaling:
  type: standard
  # type: minmax
  # type: robust
  # type: maxabs


Model:

  LinearRegression:
    fit_intercept: True

  Ridge:
    fit_intercept: True
    alpha: 10.0
    solver: 'auto'
    positive: False

  XGBoost:
    n_estimators: 200
    max_depth: 4
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1     
    reg_lambda: 1.0   
    objective: 'reg:squarederror'

  NeuralNetwork:
    hidden_layer_sizes: [64, 16]
    activation: 'relu'
    solver: 'adam'
    alpha: 0.01
    learning_rate_init: 0.001
    max_iter: 1000
    batch_size: 'auto'
    early_stopping: True

  Lasso:
    fit_intercept: True
    alpha: 0.01
    positive: False
    max_iter: 2000

  LightGBM:
    n_estimators: 200
    max_depth: 4
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0
    objective: 'regression'

save_paths:
  models_dir: "Modeling/Saved_Models"
  preprocessor_path: "Modeling/Saved_Models/preprocessor.joblib"
